/**
 * workflow.config.js – Project Workflow Configuration
 *
 * Auto-generated by: node workflow/init-project.js
 * Detected tech stack: TypeScript / Node.js
 * Generated at: 2026-04-22T10:59:26.591Z
 *
 * You can customise this file at any time.
 * Re-run: node workflow/init-project.js  to apply changes.
 *
 * NOTE: projectName, techStack, sourceExtensions, and ignoreDirs are
 * intentionally omitted. They are auto-detected at runtime by detectTechStack()
 * and do not need to be configured manually. If you want to override them,
 * uncomment and edit the overrides section below.
 */

'use strict';

module.exports = {
  // ─── Runtime-Detected (uncomment to override) ─────────────────────────────
  // These are auto-detected at init time. Only set them if the detection is wrong.
  // projectName: 'EGPSpace',
  // techStack: 'TypeScript + Node.js',
  // sourceExtensions: ['.ts', '.tsx'],
  // ignoreDirs: ['node_modules', '.git', 'dist', 'build', 'output'],

  // ─── Code Graph ──────────────────────────────────────────────────────────────
  // CodeGraph auto-scans ALL supported languages (.js, .ts, .cs, .lua, .go, .py, .dart).
  // No extensions config needed. Use scopeDirs for large monorepos only.
  codeGraph: {
    scopeDirs: [],             // Large monorepo only: ['packages/core', 'lua']. Empty = full scan
  },

  // ─── Remote Workflow Reference ──────────────────────────────────────────────
  // Point to an external WorkFlowAgent installation instead of copying workflow/
  // into this project. All IDE Agent Bridge commands will use this path.
  // Leave as null to use the local workflow/ directory inside this project.
  workflowSource: 'C:/workspace/WorkFlowAgent',

  // ─── Automated Verification Loop ─────────────────────────────────────────
  testCommand: 'npm test',
  testProfile: 'fast', // P0: fast=smoke+unit, full=smoke+unit+integration

  autoFixLoop: {
    enabled: true,
    maxFixRounds: 2,
    failOnUnfixed: false,
  },

  // ─── Project Architecture Profile ─────────────────────────────────────────
  // Auto-populated by ProjectProfiler during init. Contains deep analysis of
  // frameworks, architecture patterns, data layer, communication, testing, etc.
  // Consumed by Architect/Developer agents for context-aware decisions.
  projectProfile: {
      "root": "C:\\workspace\\EGPSpace",
      "primaryLanguage": "typescript",
      "frameworks": [
          {
              "name": "Next.js",
              "category": "frontend",
              "lang": "typescript"
          }
      ],
      "architecture": {
          "pattern": "Component-based (Unity/Game)",
          "layers": [
              "api"
          ],
          "confidence": 0.5
      },
      "dataLayer": {
          "orm": [
              "Drizzle"
          ],
          "configFiles": [],
          "databases": [
              "PostgreSQL",
              "Supabase"
          ]
      },
      "testing": {
          "frameworks": []
      },
      "communication": [],
      "infrastructure": {},
      "monorepo": {
          "isMonorepo": false,
          "tool": null,
          "packages": []
      },
      "apis": [],
      "entryPoints": [
          "src/server.ts"
      ],
      "analyzedAt": "2026-04-22T10:59:26.603Z",
      "analysisMs": 5
  },  // Will be populated by init-project.js → ProjectProfiler

  // ─── Built-in Skills ─────────────────────────────────────────────────────
  builtinSkills: [
    {
        name: "workflow-orchestration",
        description: "Multi-agent workflow orchestration SOP",
        domains: [
            "workflow",
            "orchestration"
        ]
    },
    {
        name: "code-review",
        description: "Code review checklist and best practices",
        domains: [
            "quality",
            "review"
        ]
    },
    {
        name: "typescript-dev",
        description: "TypeScript development patterns",
        domains: [
            "frontend",
            "backend",
            "typescript"
        ]
    }
],

  // ─── Default Skills ───────────────────────────────────────────────────────
  defaultSkills: {
    ".ts": "typescript-dev",
    ".tsx": "typescript-dev"
},

  // ─── Project-Specific Skills (auto-loaded in ANALYSE context) ─────────────
  // These live under .workflow/skills/ and are injected when their domains
  // match the current /wf requirement. All future /wf Agents MUST load them.
  projectSkills: [
    {
      name: "framework-boundary",
      description: "F 阶段 framework 物理分层边界 · 未来 /wf 必读",
      domains: ["framework", "refactor", "architecture", "import", "boundary"],
    },
    {
      name: "iframe-rpc-safety",
      description: "G 阶段 iframe 模板底座 + compute RPC 安全契约 · 涉及 public/templates/ 时必读",
      domains: ["iframe", "template", "rpc", "compute", "experiment-core", "physics-core"],
    },
    {
      name: "project-standards",
      description: "项目包管理器 + 端口 + 测试规约",
      domains: ["pnpm", "port", "dev-server"],
    },
  ],

  // ─── Classification Rules ─────────────────────────────────────────────────
  classificationRules: [],

  // ─── IDE Configuration (ADR-37) ────────────────────────────────────────────
  // IDE-First strategy: prefer IDE-native tools over self-built ones
  // When running inside an IDE (Cursor, VS Code:, Claude Code:, Windsurf),
  // the system will automatically detect and use IDE capabilities.
  // Self-built modules (CodeGraph, LSPAdapter) serve as fallback only.
  ide: {
    // Force IDE detection (optional)
    // forceIDE: 'vscode',        // Force specific IDE: 'vscode', 'cursor', 'claude', 'windsurf'
    // forceStandalone: false,    // Force standalone mode (no IDE) - default: false

    // Enable IDE-first routing (default: true)
    // When true, prefers IDE tools: codebase_search, grep_search, view_code_item
    // When false, uses self-built modules as primary
    ideFirstRouting: true,

    // IDE capabilities configuration (auto-detected if null)
    // Manually specify which IDE capabilities to use
    capabilities: null,
    // Example:
    // capabilities: {
    //   codebaseSearch: true,
    //   grepSearch: true,
    //   viewCodeItem: true,
    //   builtinLSP: true,
    // }
  },
};
