import type { TemplateMetadata } from '../template-registry';

/** 物理学科实验模板注册表 */
export const PHYSICS_TEMPLATES: Record<string, TemplateMetadata> = {
  'physics/buoyancy': {
    id: 'physics/buoyancy',
    subject: 'physics',
    title: '浮力原理',
    description: '探索阿基米德原理：浮力 = 液体密度 × 重力加速度 × 排开液体体积',
    icon: '🌊',
    gradient: 'from-blue-400 to-cyan-500',
    templatePath: 'physics/buoyancy.html',
    parameters: [
      { name: 'objectDensity', label: '物体密度', unit: 'kg/m³', min: 200, max: 3000, defaultValue: 800, step: 50 },
      { name: 'liquidDensity', label: '液体密度', unit: 'kg/m³', min: 800, max: 13600, defaultValue: 1000, step: 100 },
      { name: 'volume', label: '物体体积', unit: 'L', min: 0.001, max: 0.05, defaultValue: 0.01, step: 0.001 },
      { name: 'gravity', label: '重力加速度', unit: 'm/s²', min: 1, max: 20, defaultValue: 9.8, step: 0.1 },
    ],
    auditStatus: 'approved',
    auditDocPath: 'docs/audits/physics-buoyancy.md',
    lastAuditedAt: '2026-04-24',
    tags: ['mechanics', 'fluid', 'archimedes'],
    atomVersion: 'v3-component',
  },
  'physics/pressure': {
    id: 'physics/pressure',
    subject: 'physics',
    title: '压强',
    description: '探索压强公式：P = F/A',
    icon: '⚡',
    gradient: 'from-blue-400 to-cyan-500',
    templatePath: 'physics/pressure.html',
    parameters: [
      { name: 'force', label: '力', unit: 'N', min: 1, max: 1000, defaultValue: 100, step: 1 },
      { name: 'area', label: '面积', unit: 'm²', min: 0.001, max: 10, defaultValue: 1, step: 0.001 },
    ],
    auditStatus: 'approved',
    auditDocPath: 'docs/audits/physics-pressure.md',
    lastAuditedAt: '2026-04-24',
    tags: ['mechanics', 'pressure'],
  },
  'physics/density': {
    id: 'physics/density',
    subject: 'physics',
    title: '密度',
    description: '探索密度公式：ρ = m/V',
    icon: '📊',
    gradient: 'from-blue-400 to-cyan-500',
    templatePath: 'physics/density.html',
    parameters: [
      { name: 'mass', label: '质量', unit: 'kg', min: 0.1, max: 1000, defaultValue: 100, step: 0.1 },
      { name: 'volume', label: '体积', unit: 'm³', min: 0.001, max: 10, defaultValue: 1, step: 0.001 },
    ],
    auditStatus: 'approved',
    auditDocPath: 'docs/audits/physics-density.md',
    lastAuditedAt: '2026-04-24',
    tags: ['mechanics', 'density'],
  },
  'physics/work-power': {
    id: 'physics/work-power',
    subject: 'physics',
    title: '功和功率',
    description: '探索功和功率公式：W = Fd, P = W/t',
    icon: '💪',
    gradient: 'from-blue-400 to-cyan-500',
    templatePath: 'physics/work-power.html',
    parameters: [
      { name: 'force', label: '力', unit: 'N', min: 1, max: 1000, defaultValue: 100, step: 1 },
      { name: 'distance', label: '距离', unit: 'm', min: 0.1, max: 100, defaultValue: 10, step: 0.1 },
      { name: 'time', label: '时间', unit: 's', min: 1, max: 100, defaultValue: 5, step: 1 },
    ],
    auditStatus: 'approved',
    auditDocPath: 'docs/audits/physics-work-power.md',
    lastAuditedAt: '2026-04-24',
    tags: ['mechanics', 'work', 'power'],
  },
  'physics/friction': {
    id: 'physics/friction',
    subject: 'physics',
    title: '摩擦力',
    description: '探索摩擦力公式：F = μN',
    icon: '🔄',
    gradient: 'from-blue-400 to-cyan-500',
    templatePath: 'physics/friction.html',
    parameters: [
      { name: 'normalForce', label: '法向力', unit: 'N', min: 1, max: 1000, defaultValue: 100, step: 1 },
      { name: 'coefficientOfFriction', label: '摩擦系数', unit: '', min: 0, max: 1, defaultValue: 0.5, step: 0.01 },
    ],
    auditStatus: 'approved',
    auditDocPath: 'docs/audits/physics-friction.md',
    lastAuditedAt: '2026-04-24',
    tags: ['mechanics', 'friction'],
  },
  'physics/phase-change': {
    id: 'physics/phase-change',
    subject: 'physics',
    title: '相变',
    description: '探索相变过程：熔化、凝固、汽化、液化',
    icon: '🌡️',
    gradient: 'from-blue-400 to-cyan-500',
    templatePath: 'physics/phase-change.html',
    parameters: [
      { name: 'temperature', label: '温度', unit: '°C', min: -50, max: 150, defaultValue: 100, step: 1 },
      { name: 'substance', label: '物质', unit: '', min: 0, max: 1, defaultValue: 0, step: 1 },
    ],
    auditStatus: 'approved',
    auditDocPath: 'docs/audits/physics-phase-change.md',
    lastAuditedAt: '2026-04-24',
    tags: ['thermodynamics', 'phase-change'],
  },
  'physics/lever': {
    id: 'physics/lever',
    subject: 'physics',
    title: '杠杆原理',
    description: '探索力矩平衡：F1 × L1 = F2 × L2',
    icon: '⚖️',
    gradient: 'from-amber-500 to-orange-500',
    templatePath: 'physics/lever.html',
    parameters: [
      { name: 'leftForce', label: '左侧力', unit: 'N', min: 1, max: 100, defaultValue: 10, step: 1 },
      { name: 'rightForce', label: '右侧力', unit: 'N', min: 1, max: 100, defaultValue: 10, step: 1 },
      { name: 'leftArm', label: '左侧臂长', unit: 'cm', min: 10, max: 100, defaultValue: 50, step: 1 },
      { name: 'rightArm', label: '右侧臂长', unit: 'cm', min: 10, max: 100, defaultValue: 50, step: 1 },
    ],
    auditStatus: 'approved',
    auditDocPath: 'docs/audits/physics-lever.md',
    lastAuditedAt: '2026-04-24',
    tags: ['mechanics', 'torque', 'simple-machines'],
  },
  'physics/refraction': {
    id: 'physics/refraction',
    subject: 'physics',
    title: '光的折射',
    description: '探索斯涅尔定律：n1 × sin(θ1) = n2 × sin(θ2)',
    icon: '💡',
    gradient: 'from-cyan-500 to-blue-500',
    templatePath: 'physics/refraction.html',
    parameters: [
      { name: 'incidentAngle', label: '入射角', unit: '°', min: 0, max: 89, defaultValue: 30, step: 1 },
      { name: 'n1', label: '介质1折射率', unit: '', min: 1, max: 2.5, defaultValue: 1.0, step: 0.01 },
      { name: 'n2', label: '介质2折射率', unit: '', min: 1, max: 2.5, defaultValue: 1.33, step: 0.01 },
    ],
    auditStatus: 'approved',
    auditDocPath: 'docs/audits/physics-refraction.md',
    lastAuditedAt: '2026-04-24',
    tags: ['optics', 'snell', 'refraction'],
  },
  'physics/circuit': {
    id: 'physics/circuit',
    subject: 'physics',
    title: '电路串并联',
    description: '探索欧姆定律及串并联电路：I = U/R, R串 = R1+R2, 1/R并 = 1/R1 + 1/R2',
    icon: '⚡',
    gradient: 'from-emerald-500 to-teal-500',
    templatePath: 'physics/circuit.html',
    parameters: [
      { name: 'voltage', label: '电源电压', unit: 'V', min: 1, max: 24, defaultValue: 6, step: 0.1 },
      { name: 'r1', label: '电阻R1', unit: 'Ω', min: 0.5, max: 100, defaultValue: 10, step: 0.5 },
      { name: 'r2', label: '电阻R2', unit: 'Ω', min: 0.5, max: 100, defaultValue: 10, step: 0.5 },
      { name: 'topology', label: '拓扑', unit: '0=串1=并', min: 0, max: 1, defaultValue: 0, step: 1 },
    ],
    auditStatus: 'approved',
    auditDocPath: 'docs/audits/physics-circuit.md',
    lastAuditedAt: '2026-04-24',
    tags: ['electricity', 'ohm', 'circuit'],
    atomVersion: 'v3-component',
  },
  'physics/motion': {
    id: 'physics/motion',
    subject: 'physics',
    title: '匀变速直线运动',
    description: '运动学实验，展示速度、加速度与时间的关系，包含 v-t 和 s-t 图像',
    icon: '🏃',
    gradient: 'from-violet-500 to-purple-500',
    templatePath: 'physics/motion.html',
    parameters: [
      { name: 'v0', label: '初速度', unit: 'm/s', min: 0, max: 50, defaultValue: 10, step: 1 },
      { name: 'acceleration', label: '加速度', unit: 'm/s²', min: -10, max: 10, defaultValue: 2, step: 0.5 },
      { name: 'time', label: '时间', unit: 's', min: 0, max: 20, defaultValue: 5, step: 0.5 },
      { name: 'mass', label: '质量', unit: 'kg', min: 0.1, max: 10, defaultValue: 1, step: 0.1 },
    ],
    auditStatus: 'pending',
    auditDocPath: 'docs/audits/physics-motion.md',
    tags: ['kinematics', 'displacement', 'velocity', 'acceleration'],
  },
  'physics/energy': {
    id: 'physics/energy',
    subject: 'physics',
    title: '机械能守恒',
    description: '单摆运动展示动能、势能和总机械能的转换与守恒',
    icon: '🔋',
    gradient: 'from-emerald-400 to-green-600',
    templatePath: 'physics/energy.html',
    parameters: [
      { name: 'mass', label: '摆球质量', unit: 'kg', min: 0.1, max: 5, defaultValue: 1, step: 0.1 },
      { name: 'length', label: '摆线长', unit: 'm', min: 0.3, max: 2.0, defaultValue: 1.0, step: 0.05 },
      { name: 'angle', label: '释放角', unit: '°', min: 5, max: 60, defaultValue: 30, step: 1 },
      { name: 'g', label: '重力加速度', unit: 'm/s²', min: 1, max: 20, defaultValue: 9.8, step: 0.1 },
    ],
    auditStatus: 'pending',
    auditDocPath: 'docs/audits/physics-energy.md',
    tags: ['mechanics', 'energy-conservation', 'pendulum'],
  },
  'physics/waves': {
    id: 'physics/waves',
    subject: 'physics',
    title: '机械波的形成与传播',
    description: '探索机械波的传播特性：波长、频率、波速的关系 v = λf',
    icon: '🌊',
    gradient: 'from-teal-400 to-cyan-600',
    templatePath: 'physics/waves.html',
    parameters: [
      { name: 'frequency', label: '频率', unit: 'Hz', min: 0.1, max: 10, defaultValue: 1, step: 0.1 },
      { name: 'amplitude', label: '振幅', unit: 'cm', min: 0.1, max: 10, defaultValue: 2, step: 0.1 },
      { name: 'wavelength', label: '波长', unit: 'm', min: 0.1, max: 5, defaultValue: 1, step: 0.1 },
    ],
    auditStatus: 'pending',
    auditDocPath: 'docs/audits/physics-waves.md',
    tags: ['mechanics', 'waves', 'oscillation'],
  },
  'physics/electromagnetism': {
    id: 'physics/electromagnetism',
    subject: 'physics',
    title: '电磁感应',
    description: '探索法拉第电磁感应定律：感应电动势与磁通量变化率的关系',
    icon: '🧲',
    gradient: 'from-indigo-500 to-blue-600',
    templatePath: 'physics/electromagnetism.html',
    parameters: [
      { name: 'magneticField', label: '磁场强度', unit: 'T', min: 0.01, max: 2, defaultValue: 0.5, step: 0.01 },
      { name: 'coilArea', label: '线圈面积', unit: 'm²', min: 0.001, max: 0.1, defaultValue: 0.01, step: 0.001 },
      { name: 'turns', label: '线圈匝数', unit: '', min: 1, max: 1000, defaultValue: 100, step: 1 },
      { name: 'velocity', label: '运动速度', unit: 'm/s', min: 0.1, max: 10, defaultValue: 1, step: 0.1 },
    ],
    auditStatus: 'pending',
    auditDocPath: 'docs/audits/physics-electromagnetism.md',
    tags: ['electromagnetism', 'induction', 'faraday'],
  },
  'physics/reflection': {
    id: 'physics/reflection',
    subject: 'physics',
    title: '光的反射',
    description: '探索反射定律：入射角等于反射角',
    icon: '🪞',
    gradient: 'from-pink-400 to-rose-500',
    templatePath: 'physics/reflection.html',
    parameters: [
      { name: 'incidentAngle', label: '入射角', unit: '°', min: 0, max: 89, defaultValue: 30, step: 1 },
      { name: 'reflectivity', label: '反射率', unit: '', min: 0, max: 1, defaultValue: 0.9, step: 0.01 },
    ],
    auditStatus: 'pending',
    tags: ['optics', 'reflection', 'mirror'],
  },
  'physics/lens': {
    id: 'physics/lens',
    subject: 'physics',
    title: '凸透镜成像',
    description: '探索凸透镜成像规律：焦距、物距、像距的关系',
    icon: '🔍',
    gradient: 'from-amber-400 to-yellow-500',
    templatePath: 'physics/lens.html',
    parameters: [
      { name: 'focalLength', label: '焦距', unit: 'cm', min: 1, max: 50, defaultValue: 10, step: 0.5 },
      { name: 'objectDistance', label: '物距', unit: 'cm', min: 1, max: 100, defaultValue: 20, step: 0.5 },
      { name: 'objectHeight', label: '物高', unit: 'cm', min: 0.1, max: 20, defaultValue: 2, step: 0.1 },
    ],
    auditStatus: 'pending',
    tags: ['optics', 'lens', 'image-formation'],
  },
  'physics/heat': {
    id: 'physics/heat',
    subject: 'physics',
    title: '比热容实验',
    description: '探索比热容：Q = cmΔT，比较不同物质的升温速率',
    icon: '🌡️',
    gradient: 'from-orange-400 to-red-500',
    templatePath: 'physics/heat.html',
    parameters: [
      { name: 'mass', label: '质量', unit: 'kg', min: 0.01, max: 1, defaultValue: 0.1, step: 0.01 },
      { name: 'specificHeat', label: '比热容', unit: 'J/(kg·°C)', min: 100, max: 5000, defaultValue: 4200, step: 100 },
      { name: 'heatPower', label: '加热功率', unit: 'W', min: 10, max: 1000, defaultValue: 100, step: 10 },
    ],
    auditStatus: 'pending',
    tags: ['thermodynamics', 'specific-heat', 'calorimetry'],
  },
  'physics/sound': {
    id: 'physics/sound',
    subject: 'physics',
    title: '声音的特性',
    description: '探索音调、响度、音色三要素及其物理本质',
    icon: '🔊',
    gradient: 'from-purple-400 to-pink-500',
    templatePath: 'physics/sound.html',
    parameters: [
      { name: 'frequency', label: '频率', unit: 'Hz', min: 20, max: 20000, defaultValue: 440, step: 10 },
      { name: 'amplitude', label: '振幅', unit: 'mm', min: 0.1, max: 10, defaultValue: 1, step: 0.1 },
    ],
    auditStatus: 'pending',
    tags: ['acoustics', 'sound', 'frequency'],
  },
};
